### ISSUE TITLE
Add CircleCI for Python linting

### ISSUE THREAD

**Issue by jbampton** [gatsbyg/gg#7]

**Comment by bestwebua** [comment]
Hi, @jbampton. What the project stack should be?

**Comment by jbampton** [comment]
Hey @bestwebua I think we should use `ruby:2.7.0-buster-node-browsers`

I have some code from another project shown here -> 

https://github.com/slurpcode/slurp/blob/208b09f7e6aeb89365fde3d297ab6f597e9b1795/.circleci/config.yml#L9

which installs Python.  That will give us Ruby, Python and JS.
